### ISSUE TITLE
Documentation link 404

### ISSUE THREAD

**Issue by bymayo** [nystudio107/craft-emptycoalesce#1]
Clicking documentation in Craft plugin settings gives me a 404

https://github.com/nystudio107/craft-emptycoalesce/blob/58ff0b1420413e171229f5acd8237a5b186bbc55/composer.json#L17

**Comment by khalwat** [comment]
ooopsie

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-emptycoalesce/commit/2f148caaa96ce305150a3cce91e2220f655623d7
