### ISSUE TITLE
Error Attempting to Install via php craft plugin/install

### ISSUE THREAD

**Issue by richhayler** [nystudio107/craft-emptycoalesce#35]
### Describe the bug
Installation of plugin fails for Craft v4 via php craft plugin/install

Copying the shell instructions for the plugin via Craft Control panel > Plugin Store and attempting to install via the console results in an error "requirements cannot be resolved to an installable set of packages"

### To reproduce
Steps to reproduce the behaviour:
1. Copy shell cmd from the plugin page on the Craft Plugin Store
2. Execute the cmd via the console 

### Expected behaviour
Plugin should be installed

### Error
```
Root composer.json requires nystudio107/craft-emptycoalesce ^1.0 -> satisfiable by nystudio107/craft-emptycoalesce[1.0.0, ..., 1.0.6]
nystudio107/craft-emptycoalesce[1.0.0, ..., 1.0.6] require craftcms/cms ^3.0.0 -> found craftcms/cms[3.0.0, ..., 3.7.42] but it conflicts with your root composer.json require (4.0.2).
```

### Versions
- Plugin version: 1.0.6
- Craft version: 4.0.2

**Comment by khalwat** [comment]
If you do:

```
composer require nystudio107/craft-emptycoalesce "^4.0.0-beta.1" && php craft plugin/install empty-coalesce
```

...it should work for you

**Comment by richhayler** [comment]
Thanks Andrew. I went ahead with your suggestion and it's working for me. I did notice this FYI...

```
Package ueberdosis/html-to-prosemirror is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. Skipping.
```

**Comment by khalwat** [comment]
This is not a package that the Empty Coalesce plugin requires. Something else requires it.

**Comment by richhayler** [comment]
Apologies Andrew. I'm so sorry I missed this detail when interpreting the warning message. Thank you for taking you time to point this out to me.
