### ISSUE TITLE
4.0 Release

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft-emptycoalesce#36]
### Question
Hi Andrew,

when can we expect a release for this plugin for Craft 4? Besides the Beta

Thank you!

**Comment by khalwat** [comment]
The beta will be the release; I just need to tag it as such. I can do that today if you like.

**Comment by aloco** [comment]
Hi, that would be great - thank you!

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-emptycoalesce/releases/tag/4.0.0
