### ISSUE TITLE
Twig Runtime Error when evaluating key values of undefined variables with Twig filters applied

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/craft-emptycoalesce#5]
So I have this piece of code which works fine:

`{{ entry.leadTitle ??? title ??? entry.title ??? '! No title set anywhere !' }}`

So if entry is not defined it moves on. However, `entry.leadTitle` is a multiline textfield, so if it's filled in, I'd like to apply the Twig `nl2br` filter.

`{{ entry.leadTitle|nl2br ??? title ??? entry.title ??? '! No title set anywhere !' }}`

But then I get the runtime error saying entry does not exist.
For the record, the Twig `??` operator raises the same error unfortunately.

As an update I can tell that the `|t` filter doesn't throw the issue.

**Comment by khalwat** [comment]
Probably you should do it in a two-step process. Something like:

```twig
{% set text = entry.leadTitle ??? title ??? entry.title ??? '! No title set anywhere !' %}
{{ text | nl2br }}
```
