### ISSUE TITLE
Empty string default returns null.

### ISSUE THREAD

**Issue by alexroper** [nystudio107/craft-emptycoalesce#6]
If my last fallback is an empty string, the empty coalesce returns NULL. Is that the expected behavior?

Example:

```
{% set nullVal = null %}
{% set empty = '' %}

{{ dump(nullVal ??? empty ??? '') }}
{# NULL #}

{{ dump(nullVal ?? '') }}
{# string(0) "" #}

```

**Comment by alexroper** [comment]
Thinking about this again and I guess how I could see how the logic of "return the first non-empty, non-null thing" returns NULL since nothing in that chain is not-empty. But it doesn't seem intuitive.

If I wanted the last fallback to be NULL, I would write this instead:

```
{{ nullVal ??? empty ??? null }}
```

**Comment by khalwat** [comment]
Yeah I think we'll just chalk this up to a quirk of how it works I suppose.
